- name: add repo prometheus
  shell: helm repo add stable {{ url_repo_helm }}
  register: pro_add_repo

- name:
  debug: var=pro_add_repo

- name: add repo prometheus
  shell: helm repo update
  register: pro_update_repo

- name: Install Prometheus
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_result

- name:
  debug: var=prometheus_result
