---
- hosts: all
  become: yes
  user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: 'update'
    raw: 'apt update'
  - name: 'install python'
    raw: 'apt-get -y install python'
  roles:
  - { role: install_k8s, tags: ["install_k8s_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: create-cluster, tags: ["create_cluster_role"] }

- hosts: k8s-workers
  become: yes
  user: ubuntu
  roles:
  - { role: join-workers, tags: ["join_workers_role"] }


- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: install-helm, tags: ["install_helm_role"] }
